/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    FooterApp: typeof import('./src/components/FooterApp.vue')['default']
    FooterMain: typeof import('./src/components/FooterMain.vue')['default']
    HeaderApp: typeof import('./src/components/HeaderApp.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    IconBank: typeof import('./src/components/icons/IconBank.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconCreditCard: typeof import('./src/components/icons/IconCreditCard.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconImport: typeof import('./src/components/IconImport.vue')['default']
    IconLogo: typeof import('./src/components/icons/IconLogo.vue')['default']
    IconSocialRutube: typeof import('./src/components/icons/IconSocialRutube.vue')['default']
    IconSocialTelegram: typeof import('./src/components/icons/IconSocialTelegram.vue')['default']
    IconSocialVk: typeof import('./src/components/icons/IconSocialVk.vue')['default']
    IconSocialWhatsApp: typeof import('./src/components/icons/IconSocialWhatsApp.vue')['default']
    IconSocialYoutube: typeof import('./src/components/icons/IconSocialYoutube.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    Password: typeof import('primevue/password')['default']
    QueryItem: typeof import('./src/components/QueryItem.vue')['default']
    QueryLoadFile: typeof import('./src/components/QueryLoadFile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SocialR: typeof import('./src/components/icons/social-r.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
